INSERT INTO `produccion_industrial`.`supply` (`code`, `name`, `expiration_date`, `date_of_admission`, `cost`, `quantity`, `availability`, `description`, `MEASURE_id_measure`) VALUES ('1', 'pintura roja', '2019-11-11', '2019-2-11', '150', '1000', '1', 'Pntura roja de primera', '4');
INSERT INTO `produccion_industrial`.`supply` (`code`, `name`, `expiration_date`, `date_of_admission`, `cost`, `quantity`, `availability`, `description`, `MEASURE_id_measure`) VALUES ('2', 'pintura verde', '2022-11-11', '2019-2-11', '160', '500', '1', 'Pintura verde de primera', '4');
INSERT INTO `produccion_industrial`.`supply` (`code`, `name`, `expiration_date`, `date_of_admission`, `cost`, `quantity`, `availability`, `description`, `MEASURE_id_measure`) VALUES ('3', 'playera negra', '2050-11-11', '2019-2-11', '2500', '50', '1', 'playeras de primera', '5');
INSERT INTO `produccion_industrial`.`supply` (`code`, `name`, `expiration_date`, `date_of_admission`, `cost`, `quantity`, `availability`, `description`, `MEASURE_id_measure`) VALUES ('4', 'playera azule', '2050-11-11', '2019-8-11', '1200', '60', '1', 'playeras de primera', '5');
INSERT INTO `produccion_industrial`.`supply` (`code`, `name`, `expiration_date`, `date_of_admission`, `cost`, `quantity`, `availability`, `description`, `MEASURE_id_measure`) VALUES ('5', 'liston amarillo', '2050-11-11', '2019-9-11', '25', '1000', '1', 'liston de primera', '7');
INSERT INTO `produccion_industrial`.`supply` (`code`, `name`, `expiration_date`, `date_of_admission`, `cost`, `quantity`, `availability`, `description`, `MEASURE_id_measure`) VALUES ('6', 'seda azul', '2050-11-11', '2019-9-12', '200', '750', '1', 'seda de primera', '7');
INSERT INTO `produccion_industrial`.`supply` (`code`, `name`, `expiration_date`, `date_of_admission`, `cost`, `quantity`, `availability`, `description`, `MEASURE_id_measure`) VALUES ('7', 'solvente en polvo', '2022-11-11', '2019-6-6', '300', '1000', '1', 'solvente para pintura', '1');
INSERT INTO `produccion_industrial`.`supply` (`code`, `name`, `expiration_date`, `date_of_admission`, `cost`, `quantity`, `availability`, `description`, `MEASURE_id_measure`) VALUES ('8', 'hoja transfer', '2030-11-11', '2019-5-12', '75', '500', '1', 'para realizar estampados', '5');

